config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :wines do
    resources :reviews
  end
  root 'wines#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :wines
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :wine
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :wines
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wine.rb
class Wine < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :reviews

	has_attached_file :wine_img, styles: { wine_index: "250x350>", wine_show: "325x475>" }, default_url: "/images/:style/missing.png"
 	validates_attachment_content_type :wine_img, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_wine
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.wine_id = @wine.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to wine_path(@wine)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to wine_path(@wine)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to wine_path(@wine)
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_wine
			@wine = Wine.find(params[:wine_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
	before_action :find_wine, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def index
		if params[:category].blank?
			@wines = Wine.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@wines = Wine.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
		if @wine.reviews.blank?
			@average_review = 0
		else
			@average_review = @wine.reviews.average(:rating).round(2)
		end
	end

	def new
		@wine = current_user.wines.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@wine = current_user.wines.build(wine_params)
		@wine.category_id = params[:category_id]

		if @wine.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		@wine.category_id = params[:category_id]
		if @wine.update(wine_params)
			redirect_to wine_path(@wine)
		else
			render 'edit'
		end
	end

	def destroy
		@wine.destroy
		redirect_to root_path
	end

	private

		def wine_params
			params.require(:wine).permit(:name, :description, :origin, :category_id, :wine_img)
		end

		def find_wine
			@wine = Wine.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WineReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">

		<div class="container">

      <div class="image_logo">
        <%= link_to((image_tag "quick_boost_logo.png", id: "logo"), root_path) %>
      </div>

			<ul class="nav navbar-nav">
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>

			<ul class="nav navbar-nav navbar-right">

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category] == category.name %>">
								<%= link_to category.name, wines_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>


				<% if user_signed_in? %>
					<li><%= link_to "Add Boost", new_wine_path %></li>
				<% end %>

			</ul>

		</div>

	</nav>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
		<%= yield %>
	</div>
<br>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@wine, @wine.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">

	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>


	<% if user_signed_in? %>

		<% if review.user_id == current_user.id %>

			<div class="links btn-group">

				<%= link_to "Edit", edit_wine_review_path(review.wine, review), class: "btn btn-custom" %>
				<%= link_to "Delete", wine_review_path(review.wine, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>

			</div>

		<% end %>

	<% end %>

</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">

		<h1>Edit Review</h1>

		<%= simple_form_for([@wine, @review]) do |f| %>
			<div id="rating-form">
				<label>Rating</label>
			</div>
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>

	</div>

</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-review-form">

		<h1>New Review</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/wines/_form.html.erb
<%= simple_form_for @wine, :html => { :multipart => true } do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a Category") %>
	<%= f.file_field :wine_img %>
	<%= f.input :name, label: "Drink Name" %>
	<%= f.input :description %>
	<%= f.input :origin %>
	<%= f.button :submit, "Update" %>
<% end %>

app/views/wines/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-wine-form">

		<h1>Edit Drink</h1>

		<%= simple_form_for @wine, :html => { :multipart => true } do |f| %>
			<%= f.select :category_id, @categories %>
			<%= f.file_field :wine_img %>
			<%= f.input :name, label: "Drink Name" %>
			<%= f.input :description %>
			<%= f.input :origin %>
			<%= f.button :submit, "Update",  :class => "btn-custom2"  %>
		<% end %>

	</div>

</div>

app/views/wines/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @wines.count == 0 %>

	<h1>There are no wines currently in this category</h1>

<% else %>

	<div class="row">

		<% @wines.each do |wine| %>

			<div class="col-md-3">
				<a href="/wines/<%= wine.id %>">
					<%= image_tag wine.wine_img.url(:wine_index), class: "wine" %>
				</a>
			</div>

		<% end %>

	</div>

<% end %>

app/views/wines/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-wine-form">

		<h1>New Drink</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/wines/show.html.erb
<div class="row">

	<div class="col-md-4">

		<%= image_tag @wine.wine_img.url(:wine_show), class: "wine-show" %>

	</div>

	<div class="col-md-8">

		<div class="wine-info">

			<h2 class="wine-name"><%= @wine.name %></h2>
			<h3 class="wine-origin"><span>From</span> <%= @wine.origin %></h3>
			<h2 class="avg-rating">Average Rating</h2>
			<div class="average-review-rating" data-score=<%= @average_review %>></div>
			<span class="number-of-reviews">Based on <%= @wine.reviews.count %> reviews</span>
			<p class="wine-desc"><%= @wine.description %></p>

		</div>
	</div>


</div>

<div class="row">

	<div class="col-md-6">

		<div class="reviews">

			<!-- Where the reviews/ratings will go -->
			<h1>Reviews</h1>
			<%= render @wine.reviews %>

			<div>
				<%= link_to "Add Review", new_wine_review_path(@wine), class: "btn-custom" %>
			</div>

		</div>

	</div>

</div>

<div class="links btn-group">

	<%= link_to "Back", root_path, class: "btn btn-custom" %>

	<% if user_signed_in? %>

		<% if @wine.user_id == current_user.id %>

			<%= link_to "Edit", edit_wine_path(@wine), class: "btn btn-custom" %>
			<%= link_to "Delete", wine_path(@wine), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>

		<% end %>

	<% end %>

</div>


<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>